# Generated by Django 4.1.2 on 2022-10-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
